### ISSUE TITLE
WaypointOptions do not apply to all `via` waypoints

### ISSUE THREAD

**Issue by twslankard** [heremaps/here-location-services-python#10]
In order for a `via` point to be a "passthrough" waypoint, it must have `!passThrough=true` applied to it. A quick scan of the code shows that the waypoint options are not applied to each waypoint, and are only added at the very end (to the final waypoint):

https://github.com/heremaps/here-location-services-python/blob/cf841b14ba0aa149ffc84b6cd69c317b913da68c/here_location_services/routing_api.py#L100-L120

Ideally, the user should be able to specify a `WayPointOptions` object with each `via` point. This would fix the issue.

Bear with me and I can provide an example of expected versus current behavior. If possible, I will also try to submit a PR.

**Comment by sackh** [comment]
Thanks, @twslankard for raising this issue. I have fixed this issue in #11, feel free to close this issue if your expectations are met.

**Comment by twslankard** [comment]
Thanks @sackh . So far it seems to work just fine!
