### ISSUE TITLE
Wrongly type annotated get_weather_alerts method

### ISSUE THREAD

**Issue by DeemanOne** [heremaps/here-location-services-python#22]
In the type annotation for  get_weather_alerts geometry can be one of Point, LineString, Polygon, MultiPolygon.
Requesting weather alerts for a polygon results in the following error tho:

ApiError: 400, Bad Request, {"status":400,"title":"Invalid Request","code":"E611309","cause":"Unsupported geometry type 'Polygon'. Only 'Point' and 'LineString' are supported","action":null,"correlationId":null}

**Comment by sackh** [comment]
Thank you @DeemanOne for reporting this, we will look into this.

**Comment by sackh** [comment]
This is fixed in #23 only `Point` and `LineString` are supported geometries.
