### ISSUE TITLE
truckRestrictionPenalty

### ISSUE THREAD

**Issue by mightym** [heremaps/here-location-services-python#27]
Is there somewhere an option to pass in `truckRestrictionPenalty=soft` to the `truck_route` method like mentioned here https://developer.here.com/documentation/routing/dev_guide/topics/example-truck-route-violating-restriction.html ?
I dug through the code and found nothing.

**Comment by sackh** [comment]
@mightym - `truckRestrictionPenalty=soft` is part of routing API version 7 and we are supporting version 8 which is the latest version.
You can find more information about version 7 to version 8 migration [here](https://developer.here.com/documentation/routing-api/migration_guide/index.html).
`truckRestrictionPenalty` param is not there in version 8 -

Routes that violate truck restrictions:
Routing v7 had a strict approach to truck restrictions. There, no route which violated some truck restriction(s) was ever returned. It was possible to change this behavior with the truckRestrictionPenalty parameter, but even then Routing v7 provided only a generic notice: Code: routingOptionViolated, Text: truckRestriction.

In v8 if no route can be found that obeys all specified options and truck parameters, and avoids all applicable restrictions, a route that violates some of them will be returned by default. A set of critical notices explaining which restrictions could not be avoided will also be provided.

**Comment by mightym** [comment]
@sackh Ah! Awesome mate. And thanks a lot for taking your time for such an elaborated explanation.
